### ISSUE TITLE
Can we expose camelCase methods

### ISSUE THREAD

**Issue by maotora** [nextsms/js-client#8]
Hi,

Great wrapper around NextSMS!

I have a little request which may turn to a PR once accepted.

**Turning snake_case methods & variables to camelCase** 

It may sound like not much but for NodeJS/JavaScript developers we are born used to camelCase [conversion](https://github.com/felixge/node-style-guide#naming-conventions-1) and since people will be integrating this into their NodeJS programs it will be much convenient it the methods exposed from this library have a familiar syntax.

Thanks!

**Comment by alphaolomi** [comment]
Hello @maotora 

This is a very valid point, and was under consider, conversion to camelCase already started on [php client](https://github.com/nextsms/php-client) 

If you can help with that would be very helpful
Thanks
